name: Run tests

on:
  - pull_request
  - push

env:
  PERL_MM_USE_DEFAULT: 1

jobs:
  ci:
    uses: houseabsolute/workflow-perl-dzil-ci/.github/workflows/ci.yml@v0
    with:
      dist: DateTime-TimeZone
      ref: v0
      additional-modules: DateTime
