name: Run tests

on:
  - pull_request
  - push

jobs:
  diagnose-windows-datetime:
    runs-on: windows-latest
    steps:
      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: latest

      - name: Perl version
        run: perl -V

      - name: Install DateTime with cpanm (verbose)
        run: cpanm --verbose --notest DateTime
