# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.07) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Do not edit this file directly.

package DateTime::TimeZone;

use strict;

@DateTime::TimeZone::ALL =
qw(
  Africa/Abidjan
  Africa/Accra
  Africa/Addis_Ababa
  Africa/Algiers
  Africa/Asmera
  Africa/Bamako
  Africa/Bangui
  Africa/Banjul
  Africa/Bissau
  Africa/Blantyre
  Africa/Brazzaville
  Africa/Bujumbura
  Africa/Cairo
  Africa/Casablanca
  Africa/Ceuta
  Africa/Conakry
  Africa/Dakar
  Africa/Dar_es_Salaam
  Africa/Djibouti
  Africa/Douala
  Africa/El_Aaiun
  Africa/Freetown
  Africa/Gaborone
  Africa/Harare
  Africa/Johannesburg
  Africa/Kampala
  Africa/Khartoum
  Africa/Kigali
  Africa/Kinshasa
  Africa/Lagos
  Africa/Libreville
  Africa/Lome
  Africa/Luanda
  Africa/Lubumbashi
  Africa/Lusaka
  Africa/Malabo
  Africa/Maputo
  Africa/Maseru
  Africa/Mbabane
  Africa/Mogadishu
  Africa/Monrovia
  Africa/Nairobi
  Africa/Ndjamena
  Africa/Niamey
  Africa/Nouakchott
  Africa/Ouagadougou
  Africa/Porto-Novo
  Africa/Sao_Tome
  Africa/Tripoli
  Africa/Tunis
  Africa/Windhoek
  America/Adak
  America/Anchorage
  America/Anguilla
  America/Antigua
  America/Araguaina
  America/Argentina/Buenos_Aires
  America/Argentina/Catamarca
  America/Argentina/Cordoba
  America/Argentina/Jujuy
  America/Argentina/La_Rioja
  America/Argentina/Mendoza
  America/Argentina/Rio_Gallegos
  America/Argentina/San_Juan
  America/Argentina/Tucuman
  America/Argentina/Ushuaia
  America/Aruba
  America/Asuncion
  America/Atikokan
  America/Bahia
  America/Barbados
  America/Belem
  America/Belize
  America/Blanc-Sablon
  America/Boa_Vista
  America/Bogota
  America/Boise
  America/Cambridge_Bay
  America/Campo_Grande
  America/Cancun
  America/Caracas
  America/Cayenne
  America/Cayman
  America/Chicago
  America/Chihuahua
  America/Costa_Rica
  America/Cuiaba
  America/Curacao
  America/Danmarkshavn
  America/Dawson
  America/Dawson_Creek
  America/Denver
  America/Detroit
  America/Dominica
  America/Edmonton
  America/Eirunepe
  America/El_Salvador
  America/Fortaleza
  America/Glace_Bay
  America/Godthab
  America/Goose_Bay
  America/Grand_Turk
  America/Grenada
  America/Guadeloupe
  America/Guatemala
  America/Guayaquil
  America/Guyana
  America/Halifax
  America/Havana
  America/Hermosillo
  America/Indiana/Indianapolis
  America/Indiana/Knox
  America/Indiana/Marengo
  America/Indiana/Petersburg
  America/Indiana/Vevay
  America/Indiana/Vincennes
  America/Inuvik
  America/Iqaluit
  America/Jamaica
  America/Juneau
  America/Kentucky/Louisville
  America/Kentucky/Monticello
  America/La_Paz
  America/Lima
  America/Los_Angeles
  America/Maceio
  America/Managua
  America/Manaus
  America/Martinique
  America/Mazatlan
  America/Menominee
  America/Merida
  America/Mexico_City
  America/Miquelon
  America/Moncton
  America/Monterrey
  America/Montevideo
  America/Montreal
  America/Montserrat
  America/Nassau
  America/New_York
  America/Nipigon
  America/Nome
  America/Noronha
  America/North_Dakota/Center
  America/North_Dakota/New_Salem
  America/Panama
  America/Pangnirtung
  America/Paramaribo
  America/Phoenix
  America/Port-au-Prince
  America/Port_of_Spain
  America/Porto_Velho
  America/Puerto_Rico
  America/Rainy_River
  America/Rankin_Inlet
  America/Recife
  America/Regina
  America/Rio_Branco
  America/Santiago
  America/Santo_Domingo
  America/Sao_Paulo
  America/Scoresbysund
  America/St_Johns
  America/St_Kitts
  America/St_Lucia
  America/St_Thomas
  America/St_Vincent
  America/Swift_Current
  America/Tegucigalpa
  America/Thule
  America/Thunder_Bay
  America/Tijuana
  America/Toronto
  America/Tortola
  America/Vancouver
  America/Whitehorse
  America/Winnipeg
  America/Yakutat
  America/Yellowknife
  Antarctica/Casey
  Antarctica/Davis
  Antarctica/DumontDUrville
  Antarctica/Mawson
  Antarctica/McMurdo
  Antarctica/Palmer
  Antarctica/Rothera
  Antarctica/Syowa
  Antarctica/Vostok
  Asia/Aden
  Asia/Almaty
  Asia/Amman
  Asia/Anadyr
  Asia/Aqtau
  Asia/Aqtobe
  Asia/Ashgabat
  Asia/Baghdad
  Asia/Bahrain
  Asia/Baku
  Asia/Bangkok
  Asia/Beirut
  Asia/Bishkek
  Asia/Brunei
  Asia/Calcutta
  Asia/Choibalsan
  Asia/Chongqing
  Asia/Colombo
  Asia/Damascus
  Asia/Dhaka
  Asia/Dili
  Asia/Dubai
  Asia/Dushanbe
  Asia/Gaza
  Asia/Harbin
  Asia/Hong_Kong
  Asia/Hovd
  Asia/Irkutsk
  Asia/Jakarta
  Asia/Jayapura
  Asia/Jerusalem
  Asia/Kabul
  Asia/Kamchatka
  Asia/Karachi
  Asia/Kashgar
  Asia/Katmandu
  Asia/Krasnoyarsk
  Asia/Kuala_Lumpur
  Asia/Kuching
  Asia/Kuwait
  Asia/Macau
  Asia/Magadan
  Asia/Makassar
  Asia/Manila
  Asia/Muscat
  Asia/Nicosia
  Asia/Novosibirsk
  Asia/Omsk
  Asia/Oral
  Asia/Phnom_Penh
  Asia/Pontianak
  Asia/Pyongyang
  Asia/Qatar
  Asia/Qyzylorda
  Asia/Rangoon
  Asia/Riyadh
  Asia/Saigon
  Asia/Sakhalin
  Asia/Samarkand
  Asia/Seoul
  Asia/Shanghai
  Asia/Singapore
  Asia/Taipei
  Asia/Tashkent
  Asia/Tbilisi
  Asia/Tehran
  Asia/Thimphu
  Asia/Tokyo
  Asia/Ulaanbaatar
  Asia/Urumqi
  Asia/Vientiane
  Asia/Vladivostok
  Asia/Yakutsk
  Asia/Yekaterinburg
  Asia/Yerevan
  Atlantic/Azores
  Atlantic/Bermuda
  Atlantic/Canary
  Atlantic/Cape_Verde
  Atlantic/Faeroe
  Atlantic/Madeira
  Atlantic/Reykjavik
  Atlantic/South_Georgia
  Atlantic/St_Helena
  Atlantic/Stanley
  Australia/Adelaide
  Australia/Brisbane
  Australia/Broken_Hill
  Australia/Currie
  Australia/Darwin
  Australia/Hobart
  Australia/Lindeman
  Australia/Lord_Howe
  Australia/Melbourne
  Australia/Perth
  Australia/Sydney
  CST6CDT
  EST
  EST5EDT
  Europe/Amsterdam
  Europe/Andorra
  Europe/Athens
  Europe/Belgrade
  Europe/Berlin
  Europe/Brussels
  Europe/Bucharest
  Europe/Budapest
  Europe/Chisinau
  Europe/Copenhagen
  Europe/Dublin
  Europe/Gibraltar
  Europe/Helsinki
  Europe/Istanbul
  Europe/Kaliningrad
  Europe/Kiev
  Europe/Lisbon
  Europe/London
  Europe/Luxembourg
  Europe/Madrid
  Europe/Malta
  Europe/Minsk
  Europe/Monaco
  Europe/Moscow
  Europe/Oslo
  Europe/Paris
  Europe/Prague
  Europe/Riga
  Europe/Rome
  Europe/Samara
  Europe/Simferopol
  Europe/Sofia
  Europe/Stockholm
  Europe/Tallinn
  Europe/Tirane
  Europe/Uzhgorod
  Europe/Vaduz
  Europe/Vienna
  Europe/Vilnius
  Europe/Volgograd
  Europe/Warsaw
  Europe/Zaporozhye
  Europe/Zurich
  HST
  Indian/Antananarivo
  Indian/Chagos
  Indian/Christmas
  Indian/Cocos
  Indian/Comoro
  Indian/Kerguelen
  Indian/Mahe
  Indian/Maldives
  Indian/Mauritius
  Indian/Mayotte
  Indian/Reunion
  MST
  MST7MDT
  PST8PDT
  Pacific/Apia
  Pacific/Auckland
  Pacific/Chatham
  Pacific/Easter
  Pacific/Efate
  Pacific/Enderbury
  Pacific/Fakaofo
  Pacific/Fiji
  Pacific/Funafuti
  Pacific/Galapagos
  Pacific/Gambier
  Pacific/Guadalcanal
  Pacific/Guam
  Pacific/Honolulu
  Pacific/Johnston
  Pacific/Kiritimati
  Pacific/Kosrae
  Pacific/Kwajalein
  Pacific/Majuro
  Pacific/Marquesas
  Pacific/Midway
  Pacific/Nauru
  Pacific/Niue
  Pacific/Norfolk
  Pacific/Noumea
  Pacific/Pago_Pago
  Pacific/Palau
  Pacific/Pitcairn
  Pacific/Ponape
  Pacific/Port_Moresby
  Pacific/Rarotonga
  Pacific/Saipan
  Pacific/Tahiti
  Pacific/Tarawa
  Pacific/Tongatapu
  Pacific/Truk
  Pacific/Wake
  Pacific/Wallis
);

@DateTime::TimeZone::CATEGORY_NAMES =
qw(
  Africa
  America
  Antarctica
  Asia
  Atlantic
  Australia
  Europe
  Indian
  Pacific
);

%DateTime::TimeZone::CATEGORIES =
(
  'Africa' => [ qw(
    Abidjan
    Accra
    Addis_Ababa
    Algiers
    Asmera
    Bamako
    Bangui
    Banjul
    Bissau
    Blantyre
    Brazzaville
    Bujumbura
    Cairo
    Casablanca
    Ceuta
    Conakry
    Dakar
    Dar_es_Salaam
    Djibouti
    Douala
    El_Aaiun
    Freetown
    Gaborone
    Harare
    Johannesburg
    Kampala
    Khartoum
    Kigali
    Kinshasa
    Lagos
    Libreville
    Lome
    Luanda
    Lubumbashi
    Lusaka
    Malabo
    Maputo
    Maseru
    Mbabane
    Mogadishu
    Monrovia
    Nairobi
    Ndjamena
    Niamey
    Nouakchott
    Ouagadougou
    Porto-Novo
    Sao_Tome
    Tripoli
    Tunis
    Windhoek
) ],
  'America' => [ qw(
    Adak
    Anchorage
    Anguilla
    Antigua
    Araguaina
    Argentina/Buenos_Aires
    Argentina/Catamarca
    Argentina/Cordoba
    Argentina/Jujuy
    Argentina/La_Rioja
    Argentina/Mendoza
    Argentina/Rio_Gallegos
    Argentina/San_Juan
    Argentina/Tucuman
    Argentina/Ushuaia
    Aruba
    Asuncion
    Atikokan
    Bahia
    Barbados
    Belem
    Belize
    Blanc-Sablon
    Boa_Vista
    Bogota
    Boise
    Cambridge_Bay
    Campo_Grande
    Cancun
    Caracas
    Cayenne
    Cayman
    Chicago
    Chihuahua
    Costa_Rica
    Cuiaba
    Curacao
    Danmarkshavn
    Dawson
    Dawson_Creek
    Denver
    Detroit
    Dominica
    Edmonton
    Eirunepe
    El_Salvador
    Fortaleza
    Glace_Bay
    Godthab
    Goose_Bay
    Grand_Turk
    Grenada
    Guadeloupe
    Guatemala
    Guayaquil
    Guyana
    Halifax
    Havana
    Hermosillo
    Indiana/Indianapolis
    Indiana/Knox
    Indiana/Marengo
    Indiana/Petersburg
    Indiana/Vevay
    Indiana/Vincennes
    Inuvik
    Iqaluit
    Jamaica
    Juneau
    Kentucky/Louisville
    Kentucky/Monticello
    La_Paz
    Lima
    Los_Angeles
    Maceio
    Managua
    Manaus
    Martinique
    Mazatlan
    Menominee
    Merida
    Mexico_City
    Miquelon
    Moncton
    Monterrey
    Montevideo
    Montreal
    Montserrat
    Nassau
    New_York
    Nipigon
    Nome
    Noronha
    North_Dakota/Center
    North_Dakota/New_Salem
    Panama
    Pangnirtung
    Paramaribo
    Phoenix
    Port-au-Prince
    Port_of_Spain
    Porto_Velho
    Puerto_Rico
    Rainy_River
    Rankin_Inlet
    Recife
    Regina
    Rio_Branco
    Santiago
    Santo_Domingo
    Sao_Paulo
    Scoresbysund
    St_Johns
    St_Kitts
    St_Lucia
    St_Thomas
    St_Vincent
    Swift_Current
    Tegucigalpa
    Thule
    Thunder_Bay
    Tijuana
    Toronto
    Tortola
    Vancouver
    Whitehorse
    Winnipeg
    Yakutat
    Yellowknife
) ],
  'Antarctica' => [ qw(
    Casey
    Davis
    DumontDUrville
    Mawson
    McMurdo
    Palmer
    Rothera
    Syowa
    Vostok
) ],
  'Asia' => [ qw(
    Aden
    Almaty
    Amman
    Anadyr
    Aqtau
    Aqtobe
    Ashgabat
    Baghdad
    Bahrain
    Baku
    Bangkok
    Beirut
    Bishkek
    Brunei
    Calcutta
    Choibalsan
    Chongqing
    Colombo
    Damascus
    Dhaka
    Dili
    Dubai
    Dushanbe
    Gaza
    Harbin
    Hong_Kong
    Hovd
    Irkutsk
    Jakarta
    Jayapura
    Jerusalem
    Kabul
    Kamchatka
    Karachi
    Kashgar
    Katmandu
    Krasnoyarsk
    Kuala_Lumpur
    Kuching
    Kuwait
    Macau
    Magadan
    Makassar
    Manila
    Muscat
    Nicosia
    Novosibirsk
    Omsk
    Oral
    Phnom_Penh
    Pontianak
    Pyongyang
    Qatar
    Qyzylorda
    Rangoon
    Riyadh
    Saigon
    Sakhalin
    Samarkand
    Seoul
    Shanghai
    Singapore
    Taipei
    Tashkent
    Tbilisi
    Tehran
    Thimphu
    Tokyo
    Ulaanbaatar
    Urumqi
    Vientiane
    Vladivostok
    Yakutsk
    Yekaterinburg
    Yerevan
) ],
  'Atlantic' => [ qw(
    Azores
    Bermuda
    Canary
    Cape_Verde
    Faeroe
    Madeira
    Reykjavik
    South_Georgia
    St_Helena
    Stanley
) ],
  'Australia' => [ qw(
    Adelaide
    Brisbane
    Broken_Hill
    Currie
    Darwin
    Hobart
    Lindeman
    Lord_Howe
    Melbourne
    Perth
    Sydney
) ],
  'Europe' => [ qw(
    Amsterdam
    Andorra
    Athens
    Belgrade
    Berlin
    Brussels
    Bucharest
    Budapest
    Chisinau
    Copenhagen
    Dublin
    Gibraltar
    Helsinki
    Istanbul
    Kaliningrad
    Kiev
    Lisbon
    London
    Luxembourg
    Madrid
    Malta
    Minsk
    Monaco
    Moscow
    Oslo
    Paris
    Prague
    Riga
    Rome
    Samara
    Simferopol
    Sofia
    Stockholm
    Tallinn
    Tirane
    Uzhgorod
    Vaduz
    Vienna
    Vilnius
    Volgograd
    Warsaw
    Zaporozhye
    Zurich
) ],
  'Indian' => [ qw(
    Antananarivo
    Chagos
    Christmas
    Cocos
    Comoro
    Kerguelen
    Mahe
    Maldives
    Mauritius
    Mayotte
    Reunion
) ],
  'Pacific' => [ qw(
    Apia
    Auckland
    Chatham
    Easter
    Efate
    Enderbury
    Fakaofo
    Fiji
    Funafuti
    Galapagos
    Gambier
    Guadalcanal
    Guam
    Honolulu
    Johnston
    Kiritimati
    Kosrae
    Kwajalein
    Majuro
    Marquesas
    Midway
    Nauru
    Niue
    Norfolk
    Noumea
    Pago_Pago
    Palau
    Pitcairn
    Ponape
    Port_Moresby
    Rarotonga
    Saipan
    Tahiti
    Tarawa
    Tongatapu
    Truk
    Wake
    Wallis
) ],

);

%DateTime::TimeZone::ZONES_BY_COUNTRY =
(
  'gl' => [ qw(
    America/Danmarkshavn
    America/Godthab
    America/Scoresbysund
    America/Thule
) ],
  'dj' => [ qw(
    Africa/Djibouti
) ],
  'jm' => [ qw(
    America/Jamaica
) ],
  'at' => [ qw(
    Europe/Vienna
) ],
  'pg' => [ qw(
    Pacific/Port_Moresby
) ],
  'ki' => [ qw(
    Pacific/Enderbury
    Pacific/Kiritimati
    Pacific/Tarawa
) ],
  'sz' => [ qw(
    Africa/Mbabane
) ],
  'yt' => [ qw(
    Indian/Mayotte
) ],
  'bn' => [ qw(
    Asia/Brunei
) ],
  'cd' => [ qw(
    Africa/Kinshasa
    Africa/Lubumbashi
) ],
  'zm' => [ qw(
    Africa/Lusaka
) ],
  'ao' => [ qw(
    Africa/Luanda
) ],
  'bw' => [ qw(
    Africa/Gaborone
) ],
  'zw' => [ qw(
    Africa/Harare
) ],
  'vc' => [ qw(
    America/St_Vincent
) ],
  'pr' => [ qw(
    America/Puerto_Rico
) ],
  'jp' => [ qw(
    Asia/Tokyo
) ],
  'na' => [ qw(
    Africa/Windhoek
) ],
  'sh' => [ qw(
    Atlantic/St_Helena
) ],
  'tj' => [ qw(
    Asia/Dushanbe
) ],
  'lc' => [ qw(
    America/St_Lucia
) ],
  'ma' => [ qw(
    Africa/Casablanca
) ],
  'mt' => [ qw(
    Europe/Malta
) ],
  'sv' => [ qw(
    America/El_Salvador
) ],
  'vu' => [ qw(
    Pacific/Efate
) ],
  'mn' => [ qw(
    Asia/Choibalsan
    Asia/Hovd
    Asia/Ulaanbaatar
) ],
  'mp' => [ qw(
    Pacific/Saipan
) ],
  'it' => [ qw(
    Europe/Rome
) ],
  're' => [ qw(
    Indian/Reunion
) ],
  'ws' => [ qw(
    Pacific/Apia
) ],
  'eg' => [ qw(
    Africa/Cairo
) ],
  'fr' => [ qw(
    Europe/Paris
) ],
  'pw' => [ qw(
    Pacific/Palau
) ],
  'uz' => [ qw(
    Asia/Samarkand
    Asia/Tashkent
) ],
  'lr' => [ qw(
    Africa/Monrovia
) ],
  'tk' => [ qw(
    Pacific/Fakaofo
) ],
  'rw' => [ qw(
    Africa/Kigali
) ],
  'be' => [ qw(
    Europe/Brussels
) ],
  'tn' => [ qw(
    Africa/Tunis
) ],
  'um' => [ qw(
    Pacific/Johnston
    Pacific/Midway
    Pacific/Wake
) ],
  'ee' => [ qw(
    Europe/Tallinn
) ],
  'ck' => [ qw(
    Pacific/Rarotonga
) ],
  'by' => [ qw(
    Europe/Minsk
) ],
  'kr' => [ qw(
    Asia/Seoul
) ],
  'ls' => [ qw(
    Africa/Maseru
) ],
  'no' => [ qw(
    Europe/Oslo
) ],
  'sa' => [ qw(
    Asia/Riyadh
) ],
  'za' => [ qw(
    Africa/Johannesburg
) ],
  'pt' => [ qw(
    Atlantic/Azores
    Atlantic/Madeira
    Europe/Lisbon
) ],
  'bf' => [ qw(
    Africa/Ouagadougou
) ],
  'ca' => [ qw(
    America/Atikokan
    America/Blanc-Sablon
    America/Cambridge_Bay
    America/Dawson
    America/Dawson_Creek
    America/Edmonton
    America/Glace_Bay
    America/Goose_Bay
    America/Halifax
    America/Inuvik
    America/Iqaluit
    America/Moncton
    America/Montreal
    America/Nipigon
    America/Pangnirtung
    America/Rainy_River
    America/Rankin_Inlet
    America/Regina
    America/St_Johns
    America/Swift_Current
    America/Thunder_Bay
    America/Toronto
    America/Vancouver
    America/Whitehorse
    America/Winnipeg
    America/Yellowknife
) ],
  'am' => [ qw(
    Asia/Yerevan
) ],
  'cm' => [ qw(
    Africa/Douala
) ],
  'mg' => [ qw(
    Indian/Antananarivo
) ],
  'sr' => [ qw(
    America/Paramaribo
) ],
  'np' => [ qw(
    Asia/Katmandu
) ],
  'bt' => [ qw(
    Asia/Thimphu
) ],
  'pl' => [ qw(
    Europe/Warsaw
) ],
  'cf' => [ qw(
    Africa/Bangui
) ],
  'ga' => [ qw(
    Africa/Libreville
) ],
  'tm' => [ qw(
    Asia/Ashgabat
) ],
  'ae' => [ qw(
    Asia/Dubai
) ],
  'ba' => [ qw(
    Europe/Sarajevo
) ],
  'ky' => [ qw(
    America/Cayman
) ],
  'th' => [ qw(
    Asia/Bangkok
) ],
  'uk' => [ qw(
    Europe/London
) ],
  'la' => [ qw(
    Asia/Vientiane
) ],
  'cc' => [ qw(
    Indian/Cocos
) ],
  'ph' => [ qw(
    Asia/Manila
) ],
  'ni' => [ qw(
    America/Managua
) ],
  'gu' => [ qw(
    Pacific/Guam
) ],
  'nc' => [ qw(
    Pacific/Noumea
) ],
  'tf' => [ qw(
    Indian/Kerguelen
) ],
  'kz' => [ qw(
    Asia/Almaty
    Asia/Aqtau
    Asia/Aqtobe
    Asia/Oral
    Asia/Qyzylorda
) ],
  'sj' => [ qw(
    Arctic/Longyearbyen
    Atlantic/Jan_Mayen
) ],
  'mm' => [ qw(
    Asia/Rangoon
) ],
  'nr' => [ qw(
    Pacific/Nauru
) ],
  'dm' => [ qw(
    America/Dominica
) ],
  'ne' => [ qw(
    Africa/Niamey
) ],
  'ad' => [ qw(
    Europe/Andorra
) ],
  'mr' => [ qw(
    Africa/Nouakchott
) ],
  'to' => [ qw(
    Pacific/Tongatapu
) ],
  'se' => [ qw(
    Europe/Stockholm
) ],
  'az' => [ qw(
    Asia/Baku
) ],
  'af' => [ qw(
    Asia/Kabul
) ],
  'gs' => [ qw(
    Atlantic/South_Georgia
) ],
  'ng' => [ qw(
    Africa/Lagos
) ],
  'bj' => [ qw(
    Africa/Porto-Novo
) ],
  'ke' => [ qw(
    Africa/Nairobi
) ],
  'me' => [ qw(
    Europe/Podgorica
) ],
  'ax' => [ qw(
    Europe/Mariehamn
) ],
  'om' => [ qw(
    Asia/Muscat
) ],
  'vg' => [ qw(
    America/Tortola
) ],
  'vn' => [ qw(
    Asia/Saigon
) ],
  'dz' => [ qw(
    Africa/Algiers
) ],
  'ci' => [ qw(
    Africa/Abidjan
) ],
  'ye' => [ qw(
    Asia/Aden
) ],
  'lk' => [ qw(
    Asia/Colombo
) ],
  'id' => [ qw(
    Asia/Jakarta
    Asia/Jayapura
    Asia/Makassar
    Asia/Pontianak
) ],
  'fm' => [ qw(
    Pacific/Kosrae
    Pacific/Ponape
    Pacific/Truk
) ],
  'ge' => [ qw(
    Asia/Tbilisi
) ],
  'gm' => [ qw(
    Africa/Banjul
) ],
  'cx' => [ qw(
    Indian/Christmas
) ],
  'lv' => [ qw(
    Europe/Riga
) ],
  'lb' => [ qw(
    Asia/Beirut
) ],
  'ru' => [ qw(
    Asia/Anadyr
    Asia/Irkutsk
    Asia/Kamchatka
    Asia/Krasnoyarsk
    Asia/Magadan
    Asia/Novosibirsk
    Asia/Omsk
    Asia/Sakhalin
    Asia/Vladivostok
    Asia/Yakutsk
    Asia/Yekaterinburg
    Europe/Kaliningrad
    Europe/Moscow
    Europe/Samara
    Europe/Volgograd
) ],
  'fk' => [ qw(
    Atlantic/Stanley
) ],
  'de' => [ qw(
    Europe/Berlin
) ],
  'fi' => [ qw(
    Europe/Helsinki
) ],
  'mv' => [ qw(
    Indian/Maldives
) ],
  'lu' => [ qw(
    Europe/Luxembourg
) ],
  'pn' => [ qw(
    Pacific/Pitcairn
) ],
  've' => [ qw(
    America/Caracas
) ],
  'bh' => [ qw(
    Asia/Bahrain
) ],
  'gi' => [ qw(
    Europe/Gibraltar
) ],
  'ro' => [ qw(
    Europe/Bucharest
) ],
  'wf' => [ qw(
    Pacific/Wallis
) ],
  'ar' => [ qw(
    America/Argentina/Buenos_Aires
    America/Argentina/Catamarca
    America/Argentina/Cordoba
    America/Argentina/Jujuy
    America/Argentina/La_Rioja
    America/Argentina/Mendoza
    America/Argentina/Rio_Gallegos
    America/Argentina/San_Juan
    America/Argentina/Tucuman
    America/Argentina/Ushuaia
) ],
  'gp' => [ qw(
    America/Guadeloupe
) ],
  'in' => [ qw(
    Asia/Calcutta
) ],
  'tv' => [ qw(
    Pacific/Funafuti
) ],
  'vi' => [ qw(
    America/St_Thomas
) ],
  'aw' => [ qw(
    America/Aruba
) ],
  'fo' => [ qw(
    Atlantic/Faeroe
) ],
  'mx' => [ qw(
    America/Cancun
    America/Chihuahua
    America/Hermosillo
    America/Mazatlan
    America/Merida
    America/Mexico_City
    America/Monterrey
    America/Tijuana
) ],
  'sn' => [ qw(
    Africa/Dakar
) ],
  'br' => [ qw(
    America/Araguaina
    America/Bahia
    America/Belem
    America/Boa_Vista
    America/Campo_Grande
    America/Cuiaba
    America/Eirunepe
    America/Fortaleza
    America/Maceio
    America/Manaus
    America/Noronha
    America/Porto_Velho
    America/Recife
    America/Rio_Branco
    America/Sao_Paulo
) ],
  'hn' => [ qw(
    America/Tegucigalpa
) ],
  'mc' => [ qw(
    Europe/Monaco
) ],
  'gg' => [ qw(
    Europe/Guernsey
) ],
  'il' => [ qw(
    Asia/Jerusalem
) ],
  'sb' => [ qw(
    Pacific/Guadalcanal
) ],
  'do' => [ qw(
    America/Santo_Domingo
) ],
  'hu' => [ qw(
    Europe/Budapest
) ],
  'nz' => [ qw(
    Pacific/Auckland
    Pacific/Chatham
) ],
  'ps' => [ qw(
    Asia/Gaza
) ],
  'ug' => [ qw(
    Africa/Kampala
) ],
  'kh' => [ qw(
    Asia/Phnom_Penh
) ],
  'gb' => [ qw(
    Europe/London
) ],
  'tg' => [ qw(
    Africa/Lome
) ],
  'bb' => [ qw(
    America/Barbados
) ],
  'je' => [ qw(
    Europe/Jersey
) ],
  'ht' => [ qw(
    America/Port-au-Prince
) ],
  'dk' => [ qw(
    Europe/Copenhagen
) ],
  'pa' => [ qw(
    America/Panama
) ],
  'cv' => [ qw(
    Atlantic/Cape_Verde
) ],
  'qa' => [ qw(
    Asia/Qatar
) ],
  'gd' => [ qw(
    America/Grenada
) ],
  'gf' => [ qw(
    America/Cayenne
) ],
  'mo' => [ qw(
    Asia/Macau
) ],
  'km' => [ qw(
    Indian/Comoro
) ],
  'kw' => [ qw(
    Asia/Kuwait
) ],
  'hr' => [ qw(
    Europe/Zagreb
) ],
  'mq' => [ qw(
    America/Martinique
) ],
  'tc' => [ qw(
    America/Grand_Turk
) ],
  'cz' => [ qw(
    Europe/Prague
) ],
  'es' => [ qw(
    Africa/Ceuta
    Atlantic/Canary
    Europe/Madrid
) ],
  'mz' => [ qw(
    Africa/Maputo
) ],
  'bo' => [ qw(
    America/La_Paz
) ],
  'au' => [ qw(
    Australia/Adelaide
    Australia/Brisbane
    Australia/Broken_Hill
    Australia/Currie
    Australia/Darwin
    Australia/Hobart
    Australia/Lindeman
    Australia/Lord_Howe
    Australia/Melbourne
    Australia/Perth
    Australia/Sydney
) ],
  'st' => [ qw(
    Africa/Sao_Tome
) ],
  'al' => [ qw(
    Europe/Tirane
) ],
  'ir' => [ qw(
    Asia/Tehran
) ],
  'cg' => [ qw(
    Africa/Brazzaville
) ],
  'md' => [ qw(
    Europe/Chisinau
) ],
  'tr' => [ qw(
    Europe/Istanbul
) ],
  'gw' => [ qw(
    Africa/Bissau
) ],
  'gn' => [ qw(
    Africa/Conakry
) ],
  'bi' => [ qw(
    Africa/Bujumbura
) ],
  'mk' => [ qw(
    Europe/Skopje
) ],
  'gr' => [ qw(
    Europe/Athens
) ],
  'ag' => [ qw(
    America/Antigua
) ],
  'co' => [ qw(
    America/Bogota
) ],
  'si' => [ qw(
    Europe/Ljubljana
) ],
  'ai' => [ qw(
    America/Anguilla
) ],
  'aq' => [ qw(
    Antarctica/Casey
    Antarctica/Davis
    Antarctica/DumontDUrville
    Antarctica/Mawson
    Antarctica/McMurdo
    Antarctica/Palmer
    Antarctica/Rothera
    Antarctica/South_Pole
    Antarctica/Syowa
    Antarctica/Vostok
) ],
  'an' => [ qw(
    America/Curacao
) ],
  'jo' => [ qw(
    Asia/Amman
) ],
  'sm' => [ qw(
    Europe/San_Marino
) ],
  'ua' => [ qw(
    Europe/Kiev
    Europe/Simferopol
    Europe/Uzhgorod
    Europe/Zaporozhye
) ],
  'eh' => [ qw(
    Africa/El_Aaiun
) ],
  'cu' => [ qw(
    America/Havana
) ],
  'cl' => [ qw(
    America/Santiago
    Pacific/Easter
) ],
  'kn' => [ qw(
    America/St_Kitts
) ],
  'ml' => [ qw(
    Africa/Bamako
) ],
  'et' => [ qw(
    Africa/Addis_Ababa
) ],
  'sc' => [ qw(
    Indian/Mahe
) ],
  'is' => [ qw(
    Atlantic/Reykjavik
) ],
  'ms' => [ qw(
    America/Montserrat
) ],
  'nl' => [ qw(
    Europe/Amsterdam
) ],
  'hk' => [ qw(
    Asia/Hong_Kong
) ],
  'ec' => [ qw(
    America/Guayaquil
    Pacific/Galapagos
) ],
  'my' => [ qw(
    Asia/Kuala_Lumpur
    Asia/Kuching
) ],
  'cr' => [ qw(
    America/Costa_Rica
) ],
  'va' => [ qw(
    Europe/Vatican
) ],
  'io' => [ qw(
    Indian/Chagos
) ],
  'rs' => [ qw(
    Europe/Belgrade
) ],
  'sd' => [ qw(
    Africa/Khartoum
) ],
  'cn' => [ qw(
    Asia/Chongqing
    Asia/Harbin
    Asia/Kashgar
    Asia/Shanghai
    Asia/Urumqi
) ],
  'bg' => [ qw(
    Europe/Sofia
) ],
  'mh' => [ qw(
    Pacific/Kwajalein
    Pacific/Majuro
) ],
  'uy' => [ qw(
    America/Montevideo
) ],
  'bs' => [ qw(
    America/Nassau
) ],
  'py' => [ qw(
    America/Asuncion
) ],
  'mu' => [ qw(
    Indian/Mauritius
) ],
  'tl' => [ qw(
    Asia/Dili
) ],
  'li' => [ qw(
    Europe/Vaduz
) ],
  'ch' => [ qw(
    Europe/Zurich
) ],
  'kg' => [ qw(
    Asia/Bishkek
) ],
  'gh' => [ qw(
    Africa/Accra
) ],
  'nu' => [ qw(
    Pacific/Niue
) ],
  'pe' => [ qw(
    America/Lima
) ],
  'us' => [ qw(
    America/Adak
    America/Anchorage
    America/Boise
    America/Chicago
    America/Denver
    America/Detroit
    America/Indiana/Indianapolis
    America/Indiana/Knox
    America/Indiana/Marengo
    America/Indiana/Petersburg
    America/Indiana/Vevay
    America/Indiana/Vincennes
    America/Juneau
    America/Kentucky/Louisville
    America/Kentucky/Monticello
    America/Los_Angeles
    America/Menominee
    America/New_York
    America/Nome
    America/North_Dakota/Center
    America/North_Dakota/New_Salem
    America/Phoenix
    America/Shiprock
    America/Yakutat
    Pacific/Honolulu
) ],
  'bz' => [ qw(
    America/Belize
) ],
  'sl' => [ qw(
    Africa/Freetown
) ],
  'cy' => [ qw(
    Asia/Nicosia
) ],
  'im' => [ qw(
    Europe/Isle_of_Man
) ],
  'fj' => [ qw(
    Pacific/Fiji
) ],
  'ie' => [ qw(
    Europe/Dublin
) ],
  'tw' => [ qw(
    Asia/Taipei
) ],
  'kp' => [ qw(
    Asia/Pyongyang
) ],
  'pf' => [ qw(
    Pacific/Gambier
    Pacific/Marquesas
    Pacific/Tahiti
) ],
  'er' => [ qw(
    Africa/Asmera
) ],
  'iq' => [ qw(
    Asia/Baghdad
) ],
  'as' => [ qw(
    Pacific/Pago_Pago
) ],
  'mw' => [ qw(
    Africa/Blantyre
) ],
  'tz' => [ qw(
    Africa/Dar_es_Salaam
) ],
  'ly' => [ qw(
    Africa/Tripoli
) ],
  'gt' => [ qw(
    America/Guatemala
) ],
  'gy' => [ qw(
    America/Guyana
) ],
  'bm' => [ qw(
    Atlantic/Bermuda
) ],
  'gq' => [ qw(
    Africa/Malabo
) ],
  'pk' => [ qw(
    Asia/Karachi
) ],
  'lt' => [ qw(
    Europe/Vilnius
) ],
  'pm' => [ qw(
    America/Miquelon
) ],
  'sg' => [ qw(
    Asia/Singapore
) ],
  'tt' => [ qw(
    America/Port_of_Spain
) ],
  'nf' => [ qw(
    Pacific/Norfolk
) ],
  'so' => [ qw(
    Africa/Mogadishu
) ],
  'td' => [ qw(
    Africa/Ndjamena
) ],
  'sk' => [ qw(
    Europe/Bratislava
) ],
  'sy' => [ qw(
    Asia/Damascus
) ],
  'bd' => [ qw(
    Asia/Dhaka
) ],

);

%DateTime::TimeZone::LINKS =
(
  'AKST9AKDT' => 'America/Anchorage',
  'Africa/Timbuktu' => 'Africa/Bamako',
  'America/Argentina/ComodRivadavia' => 'America/Argentina/Catamarca',
  'America/Atka' => 'America/Adak',
  'America/Buenos_Aires' => 'America/Argentina/Buenos_Aires',
  'America/Catamarca' => 'America/Argentina/Catamarca',
  'America/Coral_Harbour' => 'America/Atikokan',
  'America/Cordoba' => 'America/Argentina/Cordoba',
  'America/Ensenada' => 'America/Tijuana',
  'America/Fort_Wayne' => 'America/Indiana/Indianapolis',
  'America/Indianapolis' => 'America/Indiana/Indianapolis',
  'America/Jujuy' => 'America/Argentina/Jujuy',
  'America/Knox_IN' => 'America/Indiana/Knox',
  'America/Louisville' => 'America/Kentucky/Louisville',
  'America/Mendoza' => 'America/Argentina/Mendoza',
  'America/Porto_Acre' => 'America/Rio_Branco',
  'America/Rosario' => 'America/Argentina/Cordoba',
  'America/Shiprock' => 'America/Denver',
  'America/Virgin' => 'America/St_Thomas',
  'Antarctica/South_Pole' => 'Antarctica/McMurdo',
  'Arctic/Longyearbyen' => 'Europe/Oslo',
  'Asia/Ashkhabad' => 'Asia/Ashgabat',
  'Asia/Chungking' => 'Asia/Chongqing',
  'Asia/Dacca' => 'Asia/Dhaka',
  'Asia/Istanbul' => 'Europe/Istanbul',
  'Asia/Macao' => 'Asia/Macau',
  'Asia/Tel_Aviv' => 'Asia/Jerusalem',
  'Asia/Thimbu' => 'Asia/Thimphu',
  'Asia/Ujung_Pandang' => 'Asia/Makassar',
  'Asia/Ulan_Bator' => 'Asia/Ulaanbaatar',
  'Atlantic/Jan_Mayen' => 'Europe/Oslo',
  'Australia/ACT' => 'Australia/Sydney',
  'Australia/Canberra' => 'Australia/Sydney',
  'Australia/LHI' => 'Australia/Lord_Howe',
  'Australia/NSW' => 'Australia/Sydney',
  'Australia/North' => 'Australia/Darwin',
  'Australia/Queensland' => 'Australia/Brisbane',
  'Australia/South' => 'Australia/Adelaide',
  'Australia/Tasmania' => 'Australia/Hobart',
  'Australia/Victoria' => 'Australia/Melbourne',
  'Australia/West' => 'Australia/Perth',
  'Australia/Yancowinna' => 'Australia/Broken_Hill',
  'Brazil/Acre' => 'America/Rio_Branco',
  'Brazil/DeNoronha' => 'America/Noronha',
  'Brazil/East' => 'America/Sao_Paulo',
  'Brazil/West' => 'America/Manaus',
  'Canada/Atlantic' => 'America/Halifax',
  'Canada/Central' => 'America/Winnipeg',
  'Canada/East-Saskatchewan' => 'America/Regina',
  'Canada/Eastern' => 'America/Toronto',
  'Canada/Mountain' => 'America/Edmonton',
  'Canada/Newfoundland' => 'America/St_Johns',
  'Canada/Pacific' => 'America/Vancouver',
  'Canada/Saskatchewan' => 'America/Regina',
  'Canada/Yukon' => 'America/Whitehorse',
  'Chile/Continental' => 'America/Santiago',
  'Chile/EasterIsland' => 'Pacific/Easter',
  'Cuba' => 'America/Havana',
  'Egypt' => 'Africa/Cairo',
  'Eire' => 'Europe/Dublin',
  'Etc/GMT' => 'UTC',
  'Etc/GMT+0' => 'UTC',
  'Etc/UCT' => 'UTC',
  'Etc/UTC' => 'UTC',
  'Etc/Universal' => 'UTC',
  'Etc/Zulu' => 'UTC',
  'Europe/Belfast' => 'Europe/London',
  'Europe/Bratislava' => 'Europe/Prague',
  'Europe/Guernsey' => 'Europe/London',
  'Europe/Isle_of_Man' => 'Europe/London',
  'Europe/Jersey' => 'Europe/London',
  'Europe/Ljubljana' => 'Europe/Belgrade',
  'Europe/Mariehamn' => 'Europe/Helsinki',
  'Europe/Nicosia' => 'Asia/Nicosia',
  'Europe/Podgorica' => 'Europe/Belgrade',
  'Europe/San_Marino' => 'Europe/Rome',
  'Europe/Sarajevo' => 'Europe/Belgrade',
  'Europe/Skopje' => 'Europe/Belgrade',
  'Europe/Tiraspol' => 'Europe/Chisinau',
  'Europe/Vatican' => 'Europe/Rome',
  'Europe/Zagreb' => 'Europe/Belgrade',
  'GB' => 'Europe/London',
  'GB-Eire' => 'Europe/London',
  'GMT' => 'UTC',
  'GMT+0' => 'UTC',
  'GMT-0' => 'UTC',
  'GMT0' => 'UTC',
  'Greenwich' => 'UTC',
  'Hongkong' => 'Asia/Hong_Kong',
  'Iceland' => 'Atlantic/Reykjavik',
  'Iran' => 'Asia/Tehran',
  'Israel' => 'Asia/Jerusalem',
  'JST-9' => 'Asia/Tokyo',
  'Jamaica' => 'America/Jamaica',
  'Japan' => 'Asia/Tokyo',
  'Kwajalein' => 'Pacific/Kwajalein',
  'Libya' => 'Africa/Tripoli',
  'Mexico/BajaNorte' => 'America/Tijuana',
  'Mexico/BajaSur' => 'America/Mazatlan',
  'Mexico/General' => 'America/Mexico_City',
  'NZ' => 'Pacific/Auckland',
  'NZ-CHAT' => 'Pacific/Chatham',
  'Navajo' => 'America/Denver',
  'PRC' => 'Asia/Shanghai',
  'Pacific/Samoa' => 'Pacific/Pago_Pago',
  'Pacific/Yap' => 'Pacific/Truk',
  'Poland' => 'Europe/Warsaw',
  'Portugal' => 'Europe/Lisbon',
  'ROC' => 'Asia/Taipei',
  'ROK' => 'Asia/Seoul',
  'Singapore' => 'Asia/Singapore',
  'Turkey' => 'Europe/Istanbul',
  'UCT' => 'UTC',
  'US/Alaska' => 'America/Anchorage',
  'US/Aleutian' => 'America/Adak',
  'US/Arizona' => 'America/Phoenix',
  'US/Central' => 'America/Chicago',
  'US/East-Indiana' => 'America/Indiana/Indianapolis',
  'US/Eastern' => 'America/New_York',
  'US/Hawaii' => 'Pacific/Honolulu',
  'US/Indiana-Starke' => 'America/Indiana/Knox',
  'US/Michigan' => 'America/Detroit',
  'US/Mountain' => 'America/Denver',
  'US/Pacific' => 'America/Los_Angeles',
  'US/Pacific-New' => 'America/Los_Angeles',
  'US/Samoa' => 'Pacific/Pago_Pago',
  'Universal' => 'UTC',
  'W-SU' => 'Europe/Moscow',
  'Zulu' => 'UTC'
)

;

sub all_names { wantarray ? @DateTime::TimeZone::ALL : [ @DateTime::TimeZone::ALL ] }
sub categories { wantarray ? @DateTime::TimeZone::CATEGORY_NAMES : [ @DateTime::TimeZone::CATEGORY_NAMES ] }
sub links { wantarray ? %DateTime::TimeZone::LINKS : { %DateTime::TimeZone::LINKS } }

sub names_in_category
{
    shift if $_[0]->isa('DateTime::TimeZone');
    return unless exists $DateTime::TimeZone::CATEGORIES{ $_[0] };

    return wantarray ? @{ $DateTime::TimeZone::CATEGORIES{ $_[0] } } : [ $DateTime::TimeZone::CATEGORIES{ $_[0] } ];
}

sub countries { wantarray ? ( sort keys %DateTime::TimeZone::ZONES_BY_COUNTRY ) :  [ sort keys %DateTime::TimeZone::ZONES_BY_COUNTRY ] }

sub names_in_country
{
    shift if $_[0]->isa('DateTime::TimeZone');
    return unless exists $DateTime::TimeZone::ZONES_BY_COUNTRY{ lc $_[0] };

    return wantarray ? @{ $DateTime::TimeZone::ZONES_BY_COUNTRY{ lc $_[0] } } : [ $DateTime::TimeZone::ZONES_BY_COUNTRY{ lc $_[0] } ];
}


1;

__END__

=head1 NAME

DateTime::TimeZoneCatalog - Provides a list of all valid time zone names

=head1 SYNOPSIS

See DateTime::TimeZone for usage details.

=head1 DESCRIPTION

This module contains an enumerated list of all known system timezones,
so that applications can easily present a list of timezones.

=cut

